# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
"""One-time generator for tools/tuned_config/exempt_kernels.py (B3).

Seeds the ratchet allowlist with EVERY discovered @triton.jit kernel EXCEPT the
ones backing a registered tunable loader (TUNABLE_KERNEL_IMPLS). Well-known
memory-bound kernels get a specific reason; everything else gets a generic
"not yet evaluated" reason. Run once; commit the emitted exempt_kernels.py.

    python tools/tuned_config/_gen_exempt.py > tools/tuned_config/exempt_kernels.py
"""

from tools.tuned_config.discover_kernels import discover_triton_kernels

# Registry name -> the @triton.jit kernel (module:func) the loader tunes. These
# are the compute-heavy, in-path GEMM/update kernels; their loaders register in
# vllm/utils/tuned_config_registry.py.
TUNABLE_KERNEL_IMPLS = {
    "fused_moe": "vllm.model_executor.layers.fused_moe.fused_moe:fused_moe_kernel",
    "w8a8_block_fp8": (
        "vllm.model_executor.layers.quantization.utils.fp8_utils:"
        "_w8a8_triton_block_scaled_mm"
    ),
    "w8a8_block_int8": (
        "vllm.model_executor.layers.quantization.utils.int8_utils:"
        "_w8a8_block_int8_matmul"
    ),
    "selective_state_update": (
        "vllm.model_executor.layers.mamba.ops.mamba_ssm:"
        "_selective_scan_update_kernel"
    ),
}

# Substring -> reason, for well-known memory-bound kernels. First match wins.
_SPECIFIC = [
    ("rms_norm", "memory-bound elementwise normalization; tuning <2%"),
    ("rmsnorm", "memory-bound elementwise normalization; tuning <2%"),
    ("layernorm", "memory-bound elementwise normalization; tuning <2%"),
    ("rope", "memory-bound positional rotation; tuning <2%"),
    ("rotary", "memory-bound positional rotation; tuning <2%"),
    ("silu", "memory-bound activation; tuning <2%"),
    ("gelu", "memory-bound activation; tuning <2%"),
    ("act", "memory-bound activation; tuning <2%"),
    ("quant", "memory-bound elementwise quantization; tuning <2%"),
    ("dequant", "memory-bound elementwise dequantization; tuning <2%"),
    ("copy", "memory-bound data movement; tuning <2%"),
    ("cast", "memory-bound data movement; tuning <2%"),
]

_GENERIC = "not yet evaluated for tuning; default heuristic in use"


def _reason(kernel_id: str) -> str:
    func = kernel_id.split(":", 1)[1].lower()
    for needle, reason in _SPECIFIC:
        if needle in func:
            return reason
    return _GENERIC


def main() -> None:
    discovered = discover_triton_kernels("vllm")
    impls = set(TUNABLE_KERNEL_IMPLS.values())
    exempt = sorted(discovered - impls)

    print("# SPDX-License-Identifier: Apache-2.0")
    print("# SPDX-FileCopyrightText: Copyright contributors to the vLLM project")
    print('"""Ratchet allowlist for the B3 tuned-config completeness check.')
    print()
    print("AUTO-GENERATED by tools/tuned_config/_gen_exempt.py, then committed.")
    print("Every @triton.jit kernel that is NOT backed by a registered tunable")
    print("loader must appear here with a one-line reason. This is the ratchet")
    print("baseline: the check is green today and only bites NEW kernels. The")
    print("reason requirement is the de-coercion mechanism -- CI never says")
    print('"you must tune", only "tune OR justify (and a reviewer reads why)".')
    print()
    print("TUNABLE_KERNEL_IMPLS maps each registered tunable loader to the")
    print("@triton.jit kernel it tunes; those are the kernels NOT exempted.")
    print('"""')
    print()
    print("TUNABLE_KERNEL_IMPLS: dict[str, str] = {")
    for name, impl in TUNABLE_KERNEL_IMPLS.items():
        print(f"    {name!r}: {impl!r},")
    print("}")
    print()
    print(f"# {len(exempt)} memory-bound / not-yet-evaluated kernels.")
    print("EXEMPT_KERNELS: dict[str, str] = {")
    for kid in exempt:
        print(f"    {kid!r}: {_reason(kid)!r},")
    print("}")


if __name__ == "__main__":
    main()
